# Generated by Django 3.1.1 on 2020-09-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200915_2052'),
        ('products', '0002_auto_20200915_2139'),
    ]

    operations = [
    ]
